import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  section: {
    background: "#0d0503",
    padding: "8rem 1.5rem",
    position: "relative",
  },
  container: {
    maxWidth: "800px",
    margin: "0 auto",
  },
  header: {
    textAlign: "center",
    marginBottom: "4rem",
  },
  sectionLabel: {
    fontSize: "0.8rem",
    letterSpacing: "0.5em",
    textTransform: "uppercase",
    color: "#B8964A",
    marginBottom: "0.5rem",
  },
  sectionTitle: {
    fontFamily: "var(--font-serif)",
    fontSize: "clamp(2.5rem, 5vw, 3.5rem)",
    color: "#FAF0E0",
    fontWeight: 300,
  },
  ornamentWrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "15px",
    margin: "1.5rem 0",
  },
  ornamentLine: {
    width: "40px",
    height: "1px",
    background: "linear-gradient(90deg, transparent, #B8964A, transparent)",
  },
  subtitle: {
    color: "rgba(250, 240, 224, 0.7)",
    fontSize: "0.95rem",
    lineHeight: 1.8,
  },
  glassCard: {
    background: "rgba(255, 255, 255, 0.03)",
    backdropFilter: "blur(10px)",
    border: "1px solid rgba(184, 150, 74, 0.2)",
    borderRadius: "24px",
    padding: "clamp(1.5rem, 5vw, 3rem)",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "2rem",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "0.8rem",
  },
  label: {
    fontSize: "0.75rem",
    letterSpacing: "0.2em",
    textTransform: "uppercase",
    color: "#E5C780",
    fontWeight: "bold",
  },
  input: {
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "12px",
    padding: "1rem 1.2rem",
    color: "#FAF0E0",
    fontSize: "1rem",
    outline: "none",
    transition: "all 0.3s",
  },
  twoCol: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "1.5rem",
  },
  radioGroup: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(80px, 1fr))",
    gap: "10px",
  },
  radioActive: {
    padding: "1rem",
    background: "#B8964A",
    color: "#000",
    borderRadius: "12px",
    textAlign: "center",
    cursor: "pointer",
    fontSize: "0.85rem",
    fontWeight: "bold",
    transition: "0.3s",
  },
  radioInactive: {
    padding: "1rem",
    background: "rgba(255, 255, 255, 0.05)",
    color: "#FAF0E0",
    borderRadius: "12px",
    textAlign: "center",
    cursor: "pointer",
    fontSize: "0.85rem",
    transition: "0.3s",
    border: "1px solid transparent",
  },
  submitBtn: {
    marginTop: "1rem",
    padding: "1.2rem",
    background: "linear-gradient(45deg, #B8964A, #E5C780)",
    color: "#000",
    border: "none",
    borderRadius: "12px",
    fontSize: "0.9rem",
    fontWeight: "bold",
    letterSpacing: "0.2em",
    textTransform: "uppercase",
    cursor: "pointer",
  },
  btnContent: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  error: {
    color: "#ff6b6b",
    fontSize: "0.85rem",
    textAlign: "center",
  },
  success: {
    textAlign: "center",
    padding: "2rem 0",
  },
  successIcon: {
    fontSize: "4rem",
    marginBottom: "1rem",
  },
  successTitle: {
    color: "#FAF0E0",
    fontFamily: "var(--font-serif)",
    fontSize: "2rem",
  },
  successText: {
    color: "#E5C780",
    marginTop: "1rem",
    opacity: 0.8,
  },
};