import { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  section: {
    background: "#0d0503",
    padding: "clamp(4rem, 10vw, 8rem) 1.5rem",
    position: "relative",
  },
  container: {
    maxWidth: "1100px",
    margin: "0 auto",
  },
  header: {
    textAlign: "center",
    marginBottom: "5rem",
  },
  sectionLabel: {
    fontSize: "0.7rem",
    letterSpacing: "0.5em",
    textTransform: "uppercase",
    color: "#B8964A",
    marginBottom: "1rem",
    opacity: 0.8,
  },
  sectionTitle: {
    fontFamily: "var(--font-serif)",
    fontSize: "clamp(2.5rem, 6vw, 3.5rem)",
    color: "#FAF0E0",
    fontWeight: 300,
  },
  ornamentWrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "20px",
    marginTop: "1.5rem",
  },
  ornamentLine: {
    width: "60px",
    height: "1px",
    background: "linear-gradient(90deg, transparent, #B8964A, transparent)",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(340px, 1fr))",
    gap: "4rem",
    alignItems: "start",
  },
  glassCard: {
    background: "rgba(255, 255, 255, 0.02)",
    backdropFilter: "blur(20px)",
    border: "1px solid rgba(184, 150, 74, 0.15)",
    borderRadius: "32px",
    padding: "3rem",
  },
  subTitle: {
    color: "#FAF0E0",
    fontSize: "1.5rem",
    fontFamily: "var(--font-serif)",
    fontWeight: 400,
    marginBottom: "2rem",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "1.8rem",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "0.8rem",
  },
  label: {
    fontSize: "0.65rem",
    color: "#E5C780",
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    fontWeight: 700,
  },
  input: {
    background: "rgba(255, 255, 255, 0.03)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "16px",
    padding: "1.2rem",
    color: "#FAF0E0",
    fontSize: "0.95rem",
    outline: "none",
    transition: "all 0.3s ease",
  },
  textarea: {
    background: "rgba(255, 255, 255, 0.03)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "16px",
    padding: "1.2rem",
    color: "#FAF0E0",
    fontSize: "0.95rem",
    outline: "none",
    resize: "none",
    transition: "all 0.3s ease",
  },
  submitBtn: {
    padding: "1.3rem",
    background: "linear-gradient(135deg, #B8964A 0%, #967A3B 100%)",
    color: "#0d0503",
    border: "none",
    borderRadius: "16px",
    fontWeight: 900,
    cursor: "pointer",
    textTransform: "uppercase",
    letterSpacing: "0.2em",
    marginTop: "0.5rem",
  },
  listHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "2.5rem",
    borderBottom: "1px solid rgba(184, 150, 74, 0.1)",
    paddingBottom: "1.2rem",
  },
  countBadge: {
    background: "rgba(184, 150, 74, 0.1)",
    color: "#B8964A",
    padding: "0.6rem 1.4rem",
    borderRadius: "50px",
    fontSize: "0.75rem",
    fontWeight: 600,
  },
  listContainer: {
    maxHeight: "600px",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "1.2rem",
    paddingRight: "10px",
  },
  ucapanCard: {
    background: "rgba(255, 255, 255, 0.015)",
    padding: "1.8rem",
    borderRadius: "24px",
    border: "1px solid rgba(255,255,255,0.05)",
  },
  cardLayout: {
    display: "flex",
    gap: "1.2rem",
    alignItems: "flex-start",
  },
  avatar: {
    width: "45px",
    height: "45px",
    background: "rgba(184, 150, 74, 0.15)",
    color: "#B8964A",
    borderRadius: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    fontSize: "1.1rem",
    flexShrink: 0,
    border: "1px solid rgba(184, 150, 74, 0.2)",
  },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "0.6rem",
  },
  cardName: {
    color: "#FAF0E0",
    fontWeight: 700,
    fontSize: "1rem",
  },
  cardPesan: {
    color: "rgba(250, 240, 224, 0.65)",
    lineHeight: 1.8,
    fontSize: "0.95rem",
    fontStyle: "italic",
  },
  cardWaktu: {
    color: "rgba(250, 240, 224, 0.25)",
    fontSize: "0.65rem",
    fontWeight: 500,
  },
  errorText: {
    color: "#ff8a8a",
    fontSize: "0.8rem",
    textAlign: "center",
  },
  successText: {
    color: "#B8964A",
    fontSize: "0.8rem",
    textAlign: "center",
    fontWeight: 600,
  },
  statusContainer: {
    textAlign: "center",
    padding: "4rem 0",
  },
  statusText: {
    color: "rgba(250, 240, 224, 0.3)",
    fontSize: "0.9rem",
  },
};