import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  footer: {
    position: "relative",
    background: "radial-gradient(ellipse at top, #251d14 0%, #1a1510 50%, #110d0a 100%)",
    color: "#FAF0E0",
    padding: "0 1.5rem clamp(4rem, 8vw, 6rem)",
    borderTop: "1px solid rgba(184, 150, 74, 0.15)",
    overflow: "hidden",
  },
  innerContainer: {
    maxWidth: "900px",
    margin: "0 auto",
  },
  bgGlowTop: {
    position: "absolute",
    top: "-200px",
    left: "50%",
    transform: "translateX(-50%)",
    width: "700px",
    height: "700px",
    background: "radial-gradient(circle, rgba(184, 150, 74, 0.1), transparent 65%)",
    filter: "blur(60px)",
    pointerEvents: "none",
  },
  bgGlowBottom: {
    position: "absolute",
    bottom: "-100px",
    right: "-100px",
    width: "400px",
    height: "400px",
    background: "radial-gradient(circle, rgba(123, 140, 110, 0.06), transparent 70%)",
    filter: "blur(40px)",
    pointerEvents: "none",
  },
  topAccentLine: {
    height: "2px",
    background: "linear-gradient(90deg, transparent, rgba(184, 150, 74, 0.5), transparent)",
    marginBottom: "5rem",
  },
  protokolItem: {
    textAlign: "center",
    padding: "2.5rem 1.5rem",
    background: "rgba(255, 255, 255, 0.02)",
  },
  protokolIcon: {
    fontSize: "2rem",
    display: "block",
    marginBottom: "0.75rem",
  },
  protokolTitle: {
    fontSize: "0.68rem",
    letterSpacing: "0.25em",
    textTransform: "uppercase",
    color: "#B8964A",
    marginBottom: "0.5rem",
  },
  protokolDesc: {
    fontSize: "0.82rem",
    color: "#8B7B6B",
    lineHeight: 1.7,
  },
  hashtagText: {
    color: "#D4B06A",
    display: "block",
    marginTop: "0.3rem",
    fontSize: "0.9rem",
  },
  sectionLabel: {
    fontSize: "0.68rem",
    letterSpacing: "0.35em",
    textTransform: "uppercase",
    color: "#B8964A",
    marginBottom: "1.5rem",
  },
  quote: {
    fontFamily: "var(--font-serif)",
    fontSize: "clamp(1.1rem, 2.5vw, 1.4rem)",
    fontStyle: "italic",
    color: "#D4C4A8",
    lineHeight: 1.9,
    maxWidth: "560px",
    margin: "0 auto",
  },
  quoteMark: {
    fontFamily: "Georgia, serif",
    fontSize: "3rem",
    color: "rgba(184, 150, 74, 0.2)",
    lineHeight: 0,
    verticalAlign: "-0.5rem",
    margin: "0 0.3rem",
  },
  cite: {
    display: "block",
    fontSize: "0.75rem",
    color: "#6B5B4B",
    marginTop: "1.2rem",
    letterSpacing: "0.1em",
    fontStyle: "normal",
  },
  thanksText: {
    fontSize: "0.85rem",
    textAlign: "center",
    margin: "0 auto",
    maxWidth: "520px",
    color: "#8B7B6B",
    lineHeight: 2,
  },
  familyCard: {
    marginTop: "1.5rem",
    display: "inline-block",
    padding: "1.5rem 3rem",
    border: "1px solid rgba(184, 150, 74, 0.1)",
    background: "rgba(255, 255, 255, 0.02)",
  },
  familyName: {
    fontSize: "0.9rem",
    color: "#D4C4A8",
    letterSpacing: "0.08em",
  },
  familyDivider: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    margin: "0.75rem auto",
    width: "160px",
  },
  line: {
    flex: 1,
    height: "1px",
    background: "rgba(184, 150, 74, 0.2)",
  },
  ampersandSmall: {
    fontFamily: "var(--font-serif)",
    color: "#B8964A",
    fontSize: "1.2rem",
  },
  nameGradient: {
    fontFamily: "var(--font-serif)",
    fontSize: "clamp(3rem, 8vw, 5rem)",
    fontWeight: 300,
    lineHeight: 1.1,
    letterSpacing: "0.05em",
    background: "linear-gradient(180deg, #E6C27A 0%, #B8964A 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  nameDivider: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "1.5rem",
    margin: "1rem auto",
    width: "200px",
  },
  ampersandLarge: {
    fontFamily: "var(--font-serif)",
    fontSize: "2.5rem",
    color: "#B8964A",
    fontWeight: 300,
  },
  dateText: {
    fontSize: "0.82rem",
    letterSpacing: "0.2em",
    color: "#6B5B4B",
    marginTop: "1.5rem",
    textTransform: "uppercase",
  },
  locationText: {
    fontSize: "0.72rem",
    letterSpacing: "0.2em",
    color: "#4A3A2A",
    marginTop: "0.3rem",
    textTransform: "uppercase",
  },
  topBtn: {
    padding: "0.8rem 2.5rem",
    border: "1px solid rgba(184, 150, 74, 0.4)",
    background: "transparent",
    color: "#B8964A",
    fontSize: "0.75rem",
    letterSpacing: "0.2em",
    textTransform: "uppercase",
    cursor: "pointer",
    borderRadius: "999px",
  },
  creditText: {
    textAlign: "center",
    fontSize: "0.65rem",
    color: "#3A2A1A",
    marginTop: "3rem",
    letterSpacing: "0.1em",
  },
  ornamentDivider: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "1rem",
    margin: "4rem auto",
    maxWidth: "300px",
  },
  dividerLineLeft: {
    flex: 1,
    height: "1px",
    background: "linear-gradient(90deg, transparent, rgba(184, 150, 74, 0.3))",
  },
  dividerLineRight: {
    flex: 1,
    height: "1px",
    background: "linear-gradient(90deg, rgba(184, 150, 74, 0.3), transparent)",
  },
  dividerDiamond: {
    color: "#B8964A",
    fontSize: "0.5rem",
    letterSpacing: "0.5em",
  },
};